# Start with the official Golang image that contains Go and some basic tools
FROM golang:1.22-alpine AS builder

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy go mod and sum files from the root directory
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source code from the bank directory and the shared models
COPY bank ./bank
COPY shared ./shared

# Set the working directory to bank/cmd
WORKDIR /app/bank/cmd

# Build the Go app
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

# Start a new stage from scratch
FROM alpine:latest

# Set the Current Working Directory inside the container
WORKDIR /root/

# Copy the Pre-built binary file from the previous stage
COPY --from=builder /app/bank/cmd/main .

# Copy the .env file
COPY bank/.env .

# Expose port 8081 to the outside world
EXPOSE 8082

# Command to run the executable
CMD ["./main"]